# Generated by Django 5.2.5 on 2025-08-25 13:10

import address.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("core", "0028_contactrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=254)),
                ("slug", models.SlugField(max_length=254)),
                ("description", models.TextField(blank=True)),
                (
                    "address",
                    address.models.AddressField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.address",
                    ),
                ),
                (
                    "parish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="core.parish",
                    ),
                ),
            ],
            options={
                "unique_together": {("slug", "parish")},
            },
        ),
        migrations.CreateModel(
            name="LocationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Domingo"),
                            (1, "Segunda-feira"),
                            (2, "Terça-feira"),
                            (3, "Quarta-feira"),
                            (4, "Quinta-feira"),
                            (5, "Sexta-feira"),
                            (6, "Sábado"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("mass", "Missa"), ("confession", "Confissão")],
                        default="mass",
                    ),
                ),
                ("observation", models.TextField(blank=True, default="")),
                ("verified_at", models.DateField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="locations.location",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.source",
                    ),
                ),
            ],
            options={
                "unique_together": {("location", "day", "start_time")},
            },
        ),
    ]
