"""
Import script for Goiânia parish data into Django models.

This script reads the goiania.jsonl file generated by the Goiânia scraper
and imports the data into Django models (Parish and Contact).

Usage:
    poetry run python contrib/goiania_into_django.py

Requirements:
    - goiania.jsonl file must exist in the current directory
    - Django database must be configured and migrated
    - Environment variables must be set (see contrib/env-sample)

The script will:
    1. Create the state of Goiás (GO) if it doesn't exist
    2. Create cities found in the parish data
    3. Create Parish records for each scraped parish
    4. Extract and create Contact records (phone, email, Instagram)
"""

import json
import os
import re
import sys

# Add project root to Python path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import django
from django.db.utils import IntegrityError
from django.utils.text import slugify

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "missas.settings")
django.setup()

from missas.core.models import Contact, City, Parish, State  # noqa


def extract_contact_info(times_list):
    """Extract contact information from the times array."""
    contact_info = {
        "phone": "",
        "whatsapp": "",
        "email": "",
        "instagram": "",
    }

    for item in times_list:
        if not isinstance(item, str):
            continue

        # Extract phone/WhatsApp
        if "WhatsApp" in item or "whatsapp" in item.lower():
            phone_match = re.search(r'\(?\d{2}\)?\s*\d{4,5}-?\d{4}', item)
            if phone_match:
                phone = re.sub(r'\D', '', phone_match.group())
                if len(phone) >= 10:
                    contact_info["whatsapp"] = f"+55{phone}"
        elif re.match(r'^\(?\d{2}\)?[\s-]?\d{4,5}-?\d{4}', item):
            phone = re.sub(r'\D', '', item)
            if len(phone) >= 10:
                contact_info["phone"] = f"+55{phone}"

        # Extract email
        if "@" in item and "." in item:
            email_match = re.search(r'[\w\.-]+@[\w\.-]+\.\w+', item)
            if email_match:
                contact_info["email"] = email_match.group()

        # Extract Instagram
        if item.startswith("@"):
            instagram = item.strip()
            if len(instagram) > 1 and " " not in instagram:
                contact_info["instagram"] = instagram

    return contact_info


def extract_city_name(parish_full_name):
    """Extract city name from parish full name."""
    # Parish names are in format: "Parish Name – Location – City"
    # Examples:
    # "Santo Antônio de Pádua – Conj. Morada do Morro – Senador Canedo"
    # "São João Bosco – St. Oeste – Goiânia"

    parts = parish_full_name.split("–")
    if len(parts) >= 2:
        # The city is usually the last part
        city = parts[-1].strip()
        return city
    return "Goiânia"  # Default to Goiânia if can't parse


def extract_parish_name(parish_full_name):
    """Extract clean parish name from full name."""
    # Get the first part before the first "–"
    parts = parish_full_name.split("–")
    return parts[0].strip()


# Load data
with open("./goiania.jsonl") as f:
    parishes_data = [json.loads(line) for line in f.readlines()]

# Get or create state
state, _ = State.objects.get_or_create(
    short_name="GO",
    defaults={"name": "Goiás", "slug": "goias"}
)

# Track statistics
stats = {
    "parishes_created": 0,
    "parishes_updated": 0,
    "contacts_created": 0,
    "cities_created": 0,
    "errors": 0,
}

for data in parishes_data:
    try:
        parish_full_name = data["parish_name"]
        parish_name = extract_parish_name(parish_full_name)
        city_name = extract_city_name(parish_full_name)

        # Get or create city
        city, city_created = City.objects.get_or_create(
            name=city_name,
            state=state,
            defaults={"slug": slugify(city_name)}
        )

        if city_created:
            stats["cities_created"] += 1
            print(f"✓ Created city: {city}")

        # Create or get parish
        parish, parish_created = Parish.objects.get_or_create(
            city=city,
            slug=slugify(parish_name),
            defaults={"name": parish_name}
        )

        if parish_created:
            stats["parishes_created"] += 1
            print(f"✓ Created parish: {parish}")
        else:
            stats["parishes_updated"] += 1

        # Extract and create contact information
        contact_info = extract_contact_info(data.get("times", []))

        # Only create contact if we have some information
        if any(contact_info.values()):
            try:
                contact, contact_created = Contact.objects.update_or_create(
                    parish=parish,
                    defaults=contact_info
                )

                if contact_created:
                    stats["contacts_created"] += 1
                    print(f"  ✓ Created contact for {parish.name}")
                    if contact_info["whatsapp"]:
                        print(f"    WhatsApp: {contact_info['whatsapp']}")
                    if contact_info["email"]:
                        print(f"    Email: {contact_info['email']}")
                    if contact_info["instagram"]:
                        print(f"    Instagram: {contact_info['instagram']}")

            except IntegrityError as e:
                print(f"  ✗ Error creating contact for {parish.name}: {e}")
                stats["errors"] += 1

    except Exception as e:
        print(f"✗ Error processing {data.get('parish_name', 'unknown')}: {e}")
        stats["errors"] += 1
        continue

# Print statistics
print("\n" + "=" * 80)
print("Import Summary:")
print("=" * 80)
print(f"Cities created:    {stats['cities_created']}")
print(f"Parishes created:  {stats['parishes_created']}")
print(f"Parishes updated:  {stats['parishes_updated']}")
print(f"Contacts created:  {stats['contacts_created']}")
print(f"Errors:            {stats['errors']}")
print("=" * 80)
