# Generated by Django 4.2.6 on 2023-11-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0002_state_city_squashed_0003_alter_city_slug_alter_city_unique_together",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="core.state",
            ),
        ),
    ]
