# Generated by Django 4.2.6 on 2023-11-01 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_city_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                ("slug", models.SlugField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parishes",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "unique_together": {("slug", "city")},
            },
        ),
    ]
