# Generated by Django 4.2.6 on 2023-11-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_parish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parish",
            name="slug",
            field=models.SlugField(max_length=254),
        ),
    ]
