# Generated by Django 4.2.6 on 2023-11-01 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_schedule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("parish", "day", "time")},
        ),
    ]
