# Generated by Django 5.0 on 2023-12-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_rename_time_schedule_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
