# Generated by Django 5.0 on 2023-12-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_schedule_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="type",
            field=models.CharField(
                choices=[("mass", "Missa"), ("confession", "Confissão")], default="mass"
            ),
        ),
    ]
