# Generated by Django 5.0 on 2023-12-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_schedule_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="observation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
