# Generated by Django 5.0.4 on 2024-08-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_schedule_observation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(choices=[("site", "Site")], default="site")),
                ("link", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
