# Generated by Django 5.0.4 on 2024-08-28 12:18

from django.db import migrations


def create_source(apps, schema_editor):
    Source = apps.get_model("core", "Source")
    db_alias = schema_editor.connection.alias

    Source.objects.using(db_alias).create(
        link="https://www.arquidiocesedenatal.org.br/c%C3%B3pia-hor%C3%A1rios-de-missa-2",
        description="Arquidiocese de Natal",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_source"),
    ]

    operations = [migrations.RunPython(create_source)]
