# Generated by Django 5.0.4 on 2024-08-28 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_schedule_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.source"
            ),
        ),
    ]
