# Generated by Django 5.1 on 2024-09-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_schedule_verified_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.CharField(blank=True, max_length=64)),
                ("phone", models.CharField(blank=True, max_length=16)),
                ("phone2", models.CharField(blank=True, max_length=16)),
                ("whatsapp", models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name="parish",
            name="contact",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.contact",
            ),
        ),
    ]
