# Generated by Django 5.1 on 2024-09-16 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_contact_parish_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parish",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.contact",
            ),
        ),
    ]
