# Generated by Django 5.1 on 2024-09-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_parish_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parish",
            name="contact",
        ),
        migrations.AddField(
            model_name="contact",
            name="parish",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.parish",
            ),
        ),
    ]
