# Generated by Django 5.1 on 2024-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_parish_contact_contact_parish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="facebook",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
