# Generated by Django 5.1 on 2024-09-17 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_contact_facebook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.source",
            ),
        ),
    ]
