# Generated by Django 5.1 on 2024-09-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_contact_facebook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="parish",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.parish"
            ),
        ),
    ]
