# Generated by Django 5.1 on 2024-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_schedule_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="type",
            field=models.CharField(
                choices=[("site", "Site"), ("whatsapp", "WhatsApp")], default="site"
            ),
        ),
    ]
