# Generated by Django 5.1 on 2024-09-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_source_description_alter_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="location",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
