# Generated by Django 5.1.1 on 2024-09-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_schedule_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="observation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
