# Generated by Django 5.2.7 on 2025-10-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_create_cache_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="location",
            new_name="location_name",
        ),
    ]
