# Generated by Django 5.1.6 on 2025-04-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="slug",
            field=models.SlugField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="parish",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="parish",
            name="slug",
            field=models.SlugField(max_length=128),
        ),
    ]
