# Generated by Django 5.1.6 on 2025-04-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_parish_name_alter_parish_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="location",
            new_name="location_name",
        ),
    ]
