# Generated by Django 5.2.7 on 2025-11-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_location_schedule_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
