# Generated by Django 5.2.7 on 2025-11-06 08:49

from django.db import migrations


def copy_location_name_to_location(apps, schema_editor):
    Schedule = apps.get_model("core", "Schedule")
    Location = apps.get_model("core", "Location")

    # Get all unique non-empty location_name values
    unique_location_names = (
        Schedule.objects.exclude(location_name="")
        .values_list("location_name", flat=True)
        .distinct()
    )

    # Create Location objects for each unique location_name
    location_map = {}
    for location_name in unique_location_names:
        location, _ = Location.objects.get_or_create(name=location_name)
        location_map[location_name] = location

    # Update all schedules with their corresponding location
    schedules_to_update = []
    for schedule in Schedule.objects.exclude(location_name=""):
        schedule.location = location_map[schedule.location_name]
        schedules_to_update.append(schedule)
    if schedules_to_update:
        Schedule.objects.bulk_update(schedules_to_update, ["location"])


def reverse_copy_location_name_to_location(apps, schema_editor):
    Schedule = apps.get_model("core", "Schedule")

    # Clear location foreign key on reverse
    Schedule.objects.all().update(location=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_location_schedule_location"),
    ]

    operations = [
        migrations.RunPython(
            copy_location_name_to_location,
            reverse_copy_location_name_to_location,
        ),
    ]
