# Generated by Django 5.2.7 on 2025-11-08 08:43

from django.db import migrations, models

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# missas.core.migrations.0033_populate_google_place_id


def populate_google_place_id(apps, schema_editor):
    Location = apps.get_model("core", "Location")

    for location in Location.objects.all():
        first_result = location.google_maps_response["results"][0]
        location.google_place_id = first_result["place_id"]
        location.save(update_fields=["google_place_id"])


def reverse_populate_google_place_id(apps, schema_editor):
    Location = apps.get_model("core", "Location")

    for location in Location.objects.all():
        location.google_place_id = None
        location.save(update_fields=["google_place_id"])


class Migration(migrations.Migration):

    replaces = [
        ("core", "0032_add_google_place_id_to_location"),
        ("core", "0033_populate_google_place_id"),
        ("core", "0034_make_google_place_id_required"),
        ("core", "0035_remove_location_google_maps_url"),
        ("core", "0036_rename_google_place_id_location_google_maps_place_id"),
    ]

    dependencies = [
        ("core", "0031_location_schedule_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            code=populate_google_place_id,
            reverse_code=reverse_populate_google_place_id,
        ),
        migrations.RemoveField(
            model_name="location",
            name="google_maps_url",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="google_place_id",
            new_name="google_maps_place_id",
        ),
        migrations.AlterField(
            model_name="location",
            name="google_maps_place_id",
            field=models.CharField(max_length=255),
        ),
    ]
