# Generated by Django 5.2.7 on 2025-11-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.location",
            ),
        ),
    ]
