# Generated by Django 5.2.7 on 2025-11-08 00:09

from django.db import migrations


def populate_google_place_id(apps, schema_editor):
    Location = apps.get_model("core", "Location")

    for location in Location.objects.all():
        first_result = location.google_maps_response["results"][0]
        location.google_place_id = first_result["place_id"]
        location.save(update_fields=["google_place_id"])


def reverse_populate_google_place_id(apps, schema_editor):
    Location = apps.get_model("core", "Location")

    for location in Location.objects.all():
        location.google_place_id = None
        location.save(update_fields=["google_place_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_google_place_id_to_location"),
    ]

    operations = [
        migrations.RunPython(
            populate_google_place_id,
            reverse_populate_google_place_id,
        ),
    ]
