# Generated by Django 5.2.7 on 2025-11-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_copy_location_name_to_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
