# Generated by Django 5.2.7 on 2025-11-07 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_schedule_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.location",
            ),
        ),
    ]
