# Generated by Django 5.2.7 on 2025-11-08 00:09

from django.db import migrations


def populate_google_place_id(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    for location in Location.objects.all():
        if location.google_maps_response:
            try:
                results = location.google_maps_response.get("results", [])
                if results:
                    place_id = results[0].get("place_id")
                    if place_id:
                        location.google_place_id = place_id
                        location.save(update_fields=["google_place_id"])
            except (AttributeError, KeyError):
                # Skip locations with malformed google_maps_response data
                pass


def reverse_populate_google_place_id(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_google_place_id_to_location"),
    ]

    operations = [
        migrations.RunPython(
            populate_google_place_id,
            reverse_populate_google_place_id,
        ),
    ]
