# Generated by Django 5.2.7 on 2025-11-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_populate_google_place_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="google_place_id",
            field=models.CharField(max_length=255),
        ),
    ]
