# Generated by Django 5.2.7 on 2025-11-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_make_google_place_id_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="google_maps_url",
        ),
    ]
