# Generated by Django 5.2.7 on 2025-11-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_remove_location_google_maps_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="google_place_id",
            new_name="google_maps_place_id",
        ),
    ]
