# Generated by Django 5.2.7 on 2025-11-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0032_add_google_place_id_to_location_squashed_0036_rename_google_place_id_location_google_maps_place_id",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
