# Generated by Django 5.2.7 on 2025-11-16 22:05

from django.db import migrations, models


def populate_latitude_longitude(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    db_alias = schema_editor.connection.alias

    for location in Location.objects.using(db_alias).all():
        first_result = location.google_maps_response["results"][0]
        geometry = first_result["geometry"]["location"]
        location.latitude = geometry["lat"]
        location.longitude = geometry["lng"]
        location.save(using=db_alias, update_fields=["latitude", "longitude"])


def reverse_populate_latitude_longitude(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    db_alias = schema_editor.connection.alias

    for location in Location.objects.using(db_alias).all():
        location.latitude = None
        location.longitude = None
        location.save(using=db_alias, update_fields=["latitude", "longitude"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0032_add_google_place_id_to_location_squashed_0036_rename_google_place_id_location_google_maps_place_id",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.RunPython(
            code=populate_latitude_longitude,
            reverse_code=reverse_populate_latitude_longitude,
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
