# Generated by Django 5.2.7 on 2025-11-11 00:52

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


def populate_point_from_google_response(apps, schema_editor):
    Location = apps.get_model("core", "Location")

    for location in Location.objects.all():
        try:
            results = location.google_maps_response.get("results", [])
            if results:
                geometry = results[0].get("geometry", {})
                coords = geometry.get("location", {})
                lat = coords.get("lat")
                lng = coords.get("lng")

                if lat is not None and lng is not None:
                    location.point = Point(lng, lat, srid=4326)
                    location.save(update_fields=["point"])
        except (KeyError, IndexError, AttributeError, TypeError):
            pass


def reverse_populate_point(apps, schema_editor):
    Location = apps.get_model("core", "Location")

    for location in Location.objects.all():
        location.point = None
        location.save(update_fields=["point"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0032_add_google_place_id_to_location_squashed_0036_rename_google_place_id_location_google_maps_place_id",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS postgis;",
            reverse_sql="DROP EXTENSION IF EXISTS postgis;",
        ),
        migrations.AddField(
            model_name="location",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.RunPython(
            code=populate_point_from_google_response,
            reverse_code=reverse_populate_point,
        ),
    ]
