# Generated by Django 5.2.7 on 2025-11-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0032_add_google_place_id_to_location_squashed_0036_rename_google_place_id_location_google_maps_place_id",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
    ]
