# Generated by Django 5.2.7 on 2025-11-16 18:24

from django.db import migrations


def populate_latitude_longitude(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    db_alias = schema_editor.connection.alias

    for location in Location.objects.using(db_alias).all():
        first_result = location.google_maps_response["results"][0]
        geometry = first_result["geometry"]["location"]
        location.latitude = geometry["lat"]
        location.longitude = geometry["lng"]
        location.save(using=db_alias, update_fields=["latitude", "longitude"])


def reverse_populate_latitude_longitude(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    db_alias = schema_editor.connection.alias

    for location in Location.objects.using(db_alias).all():
        location.latitude = None
        location.longitude = None
        location.save(using=db_alias, update_fields=["latitude", "longitude"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_add_latitude_longitude_to_location"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_latitude_longitude,
            reverse_code=reverse_populate_latitude_longitude,
        ),
    ]
