# Generated by Django 5.2.7 on 2025-11-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0037_add_latitude_longitude_to_location_squashed_0039_make_latitude_longitude_required",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="other_type_description",
            field=models.CharField(
                blank=True,
                help_text="Tipo de celebração quando 'Outro' for selecionado",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="type",
            field=models.CharField(
                choices=[
                    ("mass", "Missa"),
                    ("confession", "Confissão"),
                    ("other", "Outro"),
                ],
                default="mass",
            ),
        ),
    ]
