# Generated by Django 5.2.7 on 2025-11-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0037_add_latitude_longitude_to_location_squashed_0039_make_latitude_longitude_required",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
