# Generated by Django 5.2.7 on 2025-11-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_contactrequest_is_archived"),
        ("core", "0040_feedback"),
    ]

    operations = []
