# Generated by Django 6.1 on 2026-09-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0040_contactrequest_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppParish",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.parish",),
        ),
    ]
