name: "Copilot Setup Steps"
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install Python dependencies
        run: |
          docker compose up -d
          poetry install
      - name: Install pre-commit hooks
        run: |
          poetry run pre-commit install
          poetry run pre-commit install-hooks || echo "Warning: pre-commit install-hooks failed, but continuing setup"
      - name: Complete setup
        run: |
          cp contrib/env-sample .env
          poetry run python manage.py migrate
          make dbload
