name: Python application
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: |
          docker compose up -d
          poetry install
          poetry run pre-commit install
          poetry run pre-commit install-hooks || echo "Warning: Failed to install pre-commit hooks, skipping lint"
          cp contrib/env-sample .env
          poetry run python manage.py migrate
          make dbload
      - name: Run linting
        run: make lint || echo "Linting failed, but continuing CI"
      - run: make coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
