name: Cruft Update
"on":
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
permissions:
  actions: write
  contents: write
  pull-requests: write
  workflows: write
jobs:
  cruft-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install cruft
      - run: cruft update --skip-apply-ask
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update template with cruft"
          title: "Update Django template with cruft"
          body: |
            This PR updates the project with the latest changes from the Django template.

            Changes were automatically applied using `cruft update`.

            Please review the changes carefully before merging.
          branch: cruft-update
          delete-branch: true
          base: master
